INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (1, 'Tiền Chiến');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (2, 'Nhạc Trịnh');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (3, 'Thiếu Nhi');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (4, 'Cách Mạng');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (5, 'Rap Việt');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (7, 'Nhạc Sàn');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (8, 'Nhạc vàng');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (9, 'Bolero');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (10, 'Hải Ngoại');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (11, 'Cải Lương');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (12, 'Không lời');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (13, 'Guitar');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (14, 'Trữ Tình');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (15, 'Nhạc Trẻ');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (16, 'Remix Việt');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (17, 'Pop');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (18, 'Nhạc Hàn');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (19, 'Nhạc Hoa');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (20, 'Aucostic');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (22, 'Thất Tình');
INSERT INTO webmusic.theloai (Id, TenTheLoai) VALUES (23, 'Quan Họ');