INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (1, 'Duyên Phận', 1, 1, 9, 1, 'Mặt Trái Của Hạnh Phúc', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (2, 'Niềm Tin Chiến Thắng', 2, 2, 15, 0, 'Đừng Hỏi Em', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (3, 'yêu Một Người Không Sai ', 0, 0, 0, 0, 'Đừng Hỏi Em', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (4, 'Anh Thì Không', 2, 4, 15, 0, 'Đừng Hỏi Em', 0, '', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (5, 'Đâu Chỉ Riêng Em', 2, 5, 15, 0, 'Đừng Hỏi Em', 0, '', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (6, 'Đừng Hỏi Em', 2, 6, 15, 0, 'Đừng Hỏi Em', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (7, 'Cause I Love You', 3, 7, 15, 0, 'Thương Mấy Cũng Là Người Dưng', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (8, 'Thương Mấy Cũng Là Người Dưng', 3, 8, 15, 0, 'Thương Mấy Cũng Là Người Dưng', 0, '1524320593', '1524320593');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (9, 'Như Phút Ban Đầu', 3, 9, 15, 0, 'Thương Mấy Cũng Là Người Dưng', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (10, 'I Don''t Believe In You', 3, 10, 15, 0, 'Thương Mấy Cũng Là Người Dưng', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (11, 'Chạm Khẽ Tim Anh Một Chút Thôi', 3, 11, 15, 0, 'Thương Mấy Cũng Là Người Dưng', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (12, 'Dẫu Anh Không Nhìn Thấy', 3, 1, 15, 0, 'Ngắm Hoa Lệ Rơi', 0, '', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (13, 'Em Phải Quên Anh', 4, 2, 15, 0, 'Ngắm Hoa Lệ Rơi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (14, 'Ngắm Hoa Lệ Rơi', 4, 3, 15, 0, 'Ngắm Hoa Lệ Rơi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (15, 'Bên Nhau Thật Khó', 4, 4, 15, 0, 'Ngắm Hoa Lệ Rơi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (16, 'Người Anh Em', 4, 5, 15, 0, 'Ngắm Hoa Lệ Rơi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (17, 'Anh Là Của Em', 5, 6, 5, 0, 'Từng Là Tất Cả', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (18, 'Thương', 5, 7, 5, 0, 'Từng Là Tất Cả', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (19, 'Quan Trọng Là Thần Thái', 5, 8, 5, 0, 'Từng Là Tất Cả', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (20, 'Làm Sao Đây', 5, 9, 5, 0, 'Từng Là Tất Cả', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (21, 'Ai Ngờ Còn Thương', 5, 10, 5, 0, 'Từng Là Tất Cả', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (22, 'Cạn Cả Nước Mắt', 5, 11, 5, 0, 'Từng Là Tất Cả', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (23, 'Xin Đừng Lặng Im', 6, 11, 15, 0, 'Đi Để Trở Về', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (24, 'Phía Sau Một Cô Gái', 6, 11, 15, 0, 'Đi Để Trở Về', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (25, 'Đi Để Trở Về', 6, 12, 15, 0, 'Đi Để Trở Về', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (26, 'Anh Đã Quen Với Cô Đơn', 6, 13, 15, 0, 'Đi Để Trở Về', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (27, 'Vinh Quang Đang Chờ Ta', 6, 14, 15, 0, 'Đi Để Trở Về', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (28, 'Đi Và Yêu', 6, 15, 15, 0, 'Đi Để Trở Về', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (29, 'Chuyến Đi Của Năm (Đi Để Trở Về 2)', 6, 16, 15, 0, 'Đi Để Trở Về', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (30, 'Từng Ngày Em Mơ Về Anh', 6, 17, 15, 0, 'Đi Để Trở Về', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (31, 'Vài Lần Đón Đưa', 6, 18, 15, 0, 'Đi Để Trở Về', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (32, 'Ngày Mai Em Đi', 6, 19, 15, 0, 'Đi Để Trở Về', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (33, 'Đếm Ngày Xa Em', 7, 20, 15, 0, 'Quan Trọng Là Thần Thái', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (34, 'Yêu Không Nghỉ Phép', 7, 21, 15, 0, 'Quan Trọng Là Thần Thái', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (35, 'Yêu Là Tha Thu (Em Chưa 18 OST)', 7, 22, 15, 0, 'Quan Trọng Là Thần Thái', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (36, 'Thấy Là Yêu Thương', 7, 6, 15, 0, 'Quan Trọng Là Thần Thái', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (37, 'Và Như Thế', 7, 7, 15, 0, 'Quan Trọng Là Thần Thái', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (38, 'Quan Trọng Là Thần Thái', 7, 8, 15, 0, 'Quan Trọng Là Thần Thái', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (39, 'Em Chưa 18 (Em Chưa 18 OST)', 7, 9, 15, 0, 'Quan Trọng Là Thần Thái', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (40, 'Yêu Đi Đừng Sợ', 7, 10, 15, 0, 'Quan Trọng Là Thần Thái', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (41, 'Não Cá Vàng', 7, 11, 15, 0, 'Quan Trọng Là Thần Thái', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (42, 'Anh Không Đòi Quà', 7, 12, 15, 0, 'Quan Trọng Là Thần Thái', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (43, 'Em Nói Em Chán Yêu Vội Vàng', 8, 13, 15, 0, 'Hỏi Thăm Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (44, 'Anh Sẽ Yêu Người Ấy Hơn Em', 8, 14, 15, 0, 'Hỏi Thăm Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (45, 'Em Thật Là Ngốc', 8, 15, 15, 0, 'Hỏi Thăm Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (46, 'Hỏi Thăm Nhau', 8, 16, 15, 0, 'Hỏi Thăm Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (47, 'Kết Thúc Lâu Rồi', 8, 18, 15, 0, 'Hỏi Thăm Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (48, 'Anh Sẽ Yêu Người Ấy Hơn Em', 8, 19, 15, 0, 'Hỏi Thăm Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (49, 'Vợ Là Nhất', 8, 20, 15, 0, 'Hỏi Thăm Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (50, 'Ta Còn Yêu Nhau', 9, 21, 15, 0, 'Ta Còn Yêu Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (51, 'Ánh Nắng Của Anh (Chờ Em Đến Ngày Mai OST)', 9, 22, 15, 0, 'Ta Còn Yêu Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (52, 'Năm Ấy', 9, 23, 15, 0, 'Ta Còn Yêu Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (53, 'Vỡ (Siêu Sao Siêu Ngố OST)', 9, 24, 15, 0, 'Ta Còn Yêu Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (54, 'Chỉ Một Câu', 9, 25, 15, 0, 'Ta Còn Yêu Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (55, 'Giấu Mặt', 9, 26, 15, 0, 'Ta Còn Yêu Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (56, 'Cũng Đành Thôi', 9, 27, 15, 0, 'Ta Còn Yêu Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (57, 'Niệm Khúc Cuối', 9, 28, 15, 0, 'Ta Còn Yêu Nhau', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (58, 'Quăng Tao Cái Boong', 10, 1, 5, 0, 'Quăng Tao Cái Boong', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (59, 'Mình Cưới Nhau Đi', 10, 28, 5, 0, 'Quăng Tao Cái Boong', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (60, 'Quăng Tao Cái Boong', 10, 3, 5, 0, 'Quăng Tao Cái Boong', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (61, 'Cho Họ Ghét Đi Em', 10, 4, 5, 0, 'Quăng Tao Cái Boong', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (62, 'Mơ Đi Bay (Royal D Remix)', 10, 5, 5, 0, 'Quăng Tao Cái Boong', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (63, 'Quăng Tao Cái Boong (Whisky Remix)', 10, 6, 5, 0, 'Quăng Tao Cái Boong', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (64, 'Bởi Vì Em Hết Yêu Anh', 11, 7, 15, 0, 'Điều Anh Biết', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (65, 'Điều Anh Biết', 11, 8, 15, 0, 'Điều Anh Biết', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (66, 'Làm Vợ Anh Nhé', 11, 9, 15, 0, 'Điều Anh Biết', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (67, 'Yêu Từ Phía Xa', 11, 10, 15, 0, 'Điều Anh Biết', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (68, '1 2 3 4', 11, 11, 15, 0, 'Điều Anh Biết', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (69, 'Thế Giới Thứ 4 (Tự Yêu Chính Mình)', 11, 11, 15, 0, 'Điều Anh Biết', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (70, 'Điều Duy Nhất Cho Em', 11, 11, 15, 0, 'Điều Anh Biết', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (71, 'Anh Muốn Em Sống Sao', 11, 12, 15, 0, 'Điều Anh Biết', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (72, 'Chuyện Anh Vẫn Chưa Kể', 11, 13, 15, 0, 'Điều Anh Biết', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (73, 'Có Được Không Em', 11, 14, 15, 0, 'Điều Anh Biết', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (74, 'Lạc Trôi', 12, 15, 15, 0, 'Lạc Trôi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (75, 'Nơi Này Có Anh', 12, 16, 15, 0, 'Lạc Trôi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (76, 'Buông Đôi Tay Nhau Ra', 12, 17, 15, 0, 'Lạc Trôi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (77, 'Tập Sống Không Có Em', 12, 18, 15, 0, 'Lạc Trôi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (78, 'Như Ngày Hôm Qua', 12, 19, 15, 0, 'Lạc Trôi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (79, 'Âm Thầm Bên Em', 12, 20, 15, 0, 'Lạc Trôi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (80, 'Mãi Yêu Em', 12, 21, 15, 0, 'Lạc Trôi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (81, 'Chắc Ai Đó Sẽ Về', 12, 22, 15, 0, 'Lạc Trôi', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (82, 'Em Gái Mưa', 13, 6, 15, 0, 'Em Gái Mưa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (83, 'Cho Em Gần Anh Thêm Chút Nữa', 13, 7, 15, 0, 'Em Gái Mưa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (84, 'Ta Còn Thuộc Về Nhau', 13, 8, 15, 0, 'Em Gái Mưa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (85, 'Ngốc', 13, 9, 15, 0, 'Em Gái Mưa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (86, 'Anh Thế Giới Và Em', 13, 10, 15, 0, 'Cánh Hoa Tàn (Mẹ Chồng OST)', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (87, 'Người Từng Yêu Anh Rất Sâu Nặng', 13, 11, 15, 0, 'Cánh Hoa Tàn (Mẹ Chồng OST)', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (88, 'Cánh Hoa Tàn (Mẹ Chồng OST)', 13, 17, 15, 0, 'Cánh Hoa Tàn (Mẹ Chồng OST)', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (89, 'Tự Ngã Em Tự Đứng Lên', 14, 18, 15, 0, 'Đừng Cố Yêu Khi Tàn Phai', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (90, 'Cười Chưa Chắc Đã Vui', 14, 19, 15, 0, 'Đừng Cố Yêu Khi Tàn Phai', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (91, 'Nỗi Đau Tồn Tại Nơi Em', 14, 20, 15, 0, 'Đừng Cố Yêu Khi Tàn Phai', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (92, 'Vì Anh Là Gió', 14, 21, 15, 0, 'Đừng Cố Yêu Khi Tàn Phai', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (93, 'Mất Anh Trong Vòng Tay', 14, 22, 15, 0, 'Đừng Cố Yêu Khi Tàn Phai', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (94, 'Không Còn Nợ Nhau', 14, 23, 15, 0, 'Đừng Cố Yêu Khi Tàn Phai', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (95, 'Sống Xa Anh Chẳng Dễ Dàng', 15, 24, 15, 0, 'Yêu Một Người Vô Tâm', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (96, 'Trái Tim Em Cũng Biết Đau', 15, 25, 15, 0, 'Yêu Một Người Vô Tâm', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (97, 'Yêu Một Người Vô Tâm', 15, 26, 15, 0, 'Yêu Một Người Vô Tâm', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (98, 'Anh Muốn Em Sống Sao', 15, 27, 15, 0, 'Yêu Một Người Vô Tâm', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (99, 'Và Em Đã Biết Mình Yêu', 15, 1, 15, 0, 'Yêu Một Người Vô Tâm', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (100, 'Lần Đầu', 15, 28, 15, 0, 'Yêu Một Người Vô Tâm', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (101, 'Có Em Chờ', 16, 3, 15, 0, 'Có Em Chờ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (102, 'Ghen', 16, 4, 15, 0, 'Có Em Chờ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (103, 'Người Em Tìm Kiếm', 16, 5, 15, 0, 'Có Em Chờ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (104, 'Hôn Anh', 16, 6, 15, 0, 'Có Em Chờ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (105, 'Y.Ê.U (EDM Version)', 16, 7, 15, 0, 'Có Em Chờ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (106, 'Đừng Xin Lỗi Nữa', 16, 1, 15, 0, 'Có Em Chờ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (107, 'Quên', 17, 28, 15, 0, 'Quên', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (108, 'Ngỡ', 17, 3, 15, 0, 'Quên', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (109, 'Anh Yêu Em', 17, 4, 15, 0, 'Quên', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (110, 'Yêu Lại Từ Đầu', 17, 5, 15, 0, 'Quên', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (111, 'Suy Nghĩ Trong Anh', 17, 6, 15, 0, 'Quên', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (112, 'Từ Bỏ', 17, 7, 15, 0, 'Quên', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (113, 'Em Là Của Anh', 18, 1, 15, 0, 'Em Là Của Anh', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (114, 'Con Bướm Xuân', 18, 28, 15, 0, 'Em Là Của Anh', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (115, 'Chúc Mừng Năm Mới', 18, 3, 15, 0, 'Em Là Của Anh', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (116, 'Không Cảm Xúc', 18, 4, 15, 0, 'Em Là Của Anh', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (117, 'Còn Lại Gì Sau Cơn Mưa', 18, 5, 15, 0, 'Em Là Của Anh', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (118, 'Nơi Ấy Con Tìm Về', 18, 6, 15, 0, 'Em Là Của Anh', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (119, 'Cớ Sao Giờ Lại Chia Xa', 20, 9, 15, 0, 'Gửi Anh Xa Nhớ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (120, 'Mình Yêu Nhau Đi', 20, 10, 15, 0, 'Gửi Anh Xa Nhớ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (121, 'Gửi Anh Xa Nhớ', 20, 11, 15, 0, 'Gửi Anh Xa Nhớ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (122, 'Nói Thương Nhau Thì Đừng Làm Trái Tim Em Đau', 20, 17, 15, 0, 'Gửi Anh Xa Nhớ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (123, 'Chỉ Là Em Giấu Đi', 20, 18, 15, 0, 'Gửi Anh Xa Nhớ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (124, 'Em Muốn', 20, 19, 15, 0, 'Gửi Anh Xa Nhớ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (125, 'Vâng Anh Đi Đi', 20, 20, 15, 0, 'Gửi Anh Xa Nhớ', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (126, 'Đêm Giao Thừa Nghe Bài Vọng Cổ', 21, 21, 14, 0, 'Vùng Lá Me Bay', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (127, 'Vùng Lá Me Bay', 21, 22, 14, 0, 'Vùng Lá Me Bay', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (128, 'Vì Lòng Còn Thương', 21, 9, 14, 0, 'Vùng Lá Me Bay', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (129, 'Sau Lần Hẹn', 21, 10, 14, 0, 'Vùng Lá Me Bay', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (132, 'Nếu Chúng Mình Cách Trở', 22, 18, 9, 0, 'Đôi Mắt Người Xưa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (133, 'Liên Khúc Thành Phố Buồn, Giọt Lệ Sầu', 22, 19, 9, 0, 'Đôi Mắt Người Xưa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (134, 'Đắp Mộ Cuộc Tình', 22, 20, 9, 0, 'Đôi Mắt Người Xưa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (135, 'Lại Nhớ Người Yêu', 22, 21, 9, 0, 'Đôi Mắt Người Xưa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (136, 'Đôi Mắt Người Xưa', 22, 22, 9, 0, 'Đôi Mắt Người Xưa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (137, 'Người Yêu Cô Đơn', 22, 6, 9, 0, 'Đôi Mắt Người Xưa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (138, 'Tình Đơn Phương', 23, 9, 15, 0, 'Tình Khúc Vàng', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (139, 'Tình Khúc Vàng', 23, 10, 15, 0, 'Tình Khúc Vàng', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (140, 'Kiếp Ve Sầu', 23, 11, 15, 0, 'Tình Khúc Vàng', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (141, 'Ảo Mộng Tình Yêu', 23, 17, 15, 0, 'Tình Khúc Vàng', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (142, 'Mưa Buồn', 23, 18, 15, 0, 'Tình Khúc Vàng', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (143, 'Mưa Bụi 2', 23, 19, 15, 0, 'Tình Khúc Vàng', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (144, 'Giới Hạn Nào Cho Chúng Ta', 24, 20, 15, 0, 'Giây Phút Chia Xa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (145, 'Giây Phút Chia Xa', 24, 21, 15, 0, 'Giây Phút Chia Xa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (146, 'Bài Ca Tết Cho Em', 24, 22, 15, 0, 'Giây Phút Chia Xa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (147, 'Xin Lỗi Tình Yêu', 24, 9, 15, 0, 'Giây Phút Chia Xa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (148, 'Bình Minh Sẽ Mang Em Đi', 24, 10, 15, 0, 'Giây Phút Chia Xa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (149, 'Ta Đi Tìm Em', 24, 11, 15, 0, 'Giây Phút Chia Xa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (150, 'Tình Ơi Xin Ngủ Yên', 24, 17, 15, 0, 'Giây Phút Chia Xa', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (151, 'Tìm Lại Bầu Trời', 25, 28, 15, 0, 'Tìm Lại Bầu Trời', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (152, 'Nắm Lấy Tay Anh', 25, 3, 15, 0, 'Tìm Lại Bầu Trời', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (153, 'Anh Nhớ Em', 25, 4, 15, 0, 'Tìm Lại Bầu Trời', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (154, 'Vì Người Không Xứng Đáng', 25, 5, 15, 0, 'Tìm Lại Bầu Trời', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (155, 'Cầu Vồng Khuyết', 25, 6, 15, 0, 'Tìm Lại Bầu Trời', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (156, 'Save Me', 26, 31, 17, 0, 'Tìm Lại Bầu Trời', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (157, 'We Don''t Talk Anymore', 27, 32, 17, 0, 'We Don''t Talk Anymore (Heyder Remix)', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (158, 'Good For You', 27, 32, 17, 0, 'We Don''t Talk Anymore (Heyder Remix)', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (159, 'The Heart Wants What It Wants', 27, 32, 17, 0, 'We Don''t Talk Anymore (Heyder Remix)', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (161, 'Love You Like A Love Song', 27, 32, 17, 0, 'We Don''t Talk Anymore (Heyder Remix)', 0, null, null);
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (162, 'Same Old Love', 27, 32, 17, 0, 'We Don''t Talk Anymore (Heyder Remix)', 0, '1524552111', '1524552111');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (163, 'Love Yourself', 28, 33, 17, 0, 'What Do You Mean?', 0, '1524547173', '1524547173');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (164, 'What Do You Mean?', 28, 33, 17, 0, 'What Do You Mean?', 0, '1524546485', '1524546485');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (165, 'Sorry', 28, 33, 17, 0, 'What Do You Mean?', 0, '1524547191', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (166, 'Cold Water', 28, 33, 17, 0, 'What Do You Mean?', 0, '1524547017', '1524547017');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (167, 'Let Me Love You', 28, 33, 17, 0, 'What Do You Mean?', 0, '1524546800', '1524546800');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (168, 'Despacito (Remix)', 28, 33, 17, 0, 'What Do You Mean?', 0, '1524546271', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (169, 'Baby', 28, 33, 17, 0, 'What Do You Mean?', 0, '1524546614', '1524546614');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (170, 'Look What You Made Me Do', 29, 30, 17, 0, 'Look What You Made Me Do', 0, '1524546179', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (171, 'Blank Space', 29, 30, 17, 0, 'Look What You Made Me Do', 0, '1524546877', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (172, 'Shake It Off', 29, 30, 17, 0, 'Look What You Made Me Do', 0, '1524546829', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (173, 'Gorgeous', 29, 30, 17, 0, 'Look What You Made Me Do', 0, '1524548157', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (174, 'Wildest Dreams', 29, 30, 17, 1, 'Look What You Made Me Do', 0, '1524548230', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (175, 'I Knew You Were Trouble', 29, 29, 17, 1, 'Look What You Made Me Do', 0, '1524548258', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (176, 'You Belong With Me', 5, 29, 17, 1, 'Look What You Made Me Do', 0, '1524549683', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (177, 'Teardrops On My Guitar', 2, 29, 17, 1, 'Look What You Made Me Do', 0, '1524550421', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (179, 'Vì Tui Ế', 30, 18, 5, 1, 'Xoá Đi Quá Khứ', 0, '1524551625', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (180, 'Đừng Thức Khuya Nữa', 30, 17, 5, 1, 'Xoá Đi Quá Khứ', 0, '1524551471', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (181, 'Có Bao Giờ Không Anh', 30, 28, 5, 1, 'Xoá Đi Quá Khứ', 0, '1524551341', '');
INSERT INTO webmusic.baihat (Id, TenBaiHat, CaSi, NhacSi, TheLoai, LuotNghe, Album, PlaylistId, Audio, Lyric) VALUES (190, 'Bâng khuâng', 31, 19, 5, 0, '', 0, '1524545581', '1524545581');