INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (1, 'Nguyễn Văn Chung');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (2, 'Tiên Cookie');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (3, 'Nguyễn Văn Đông');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (4, 'Nguyễn Vĩnh Tiến');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (5, 'Chế Linh');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (6, 'Chi Dân');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (7, '
Kai Đinh');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (8, 'Nguyễn Đình Bảng');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (9, 'Nguyễn Đức Toàn');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (10, 'Phan Mạnh Quỳnh');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (11, 'Soobin Hoàng Sơn');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (12, 'Tiên Tiên');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (13, 'Tô Thanh Tùng');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (14, 'Tăng Nhật Tuệ');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (15, 'Tâm Anh');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (16, 'Mỹ Tâm');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (17, 'Thái Thịnh');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (18, 'Thanh Bình');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (19, 'Thanh Sơn');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (20, 'Thanh Tùng');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (21, 'Thăng Long');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (22, 'Phạm Toàn Thắng');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (23, 'Thập Nhất');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (24, 'Thế Hiển');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (25, 'Thế Song');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (26, 'Thuận Yến');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (27, 'Thủy Tiên');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (28, 'Tiên Cookie');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (29, ' Richard Fairbrass');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (30, 'Jack Antonof');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (31, 'Brian May');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (32, 'Charlie Puth');
INSERT INTO webmusic.nhacsi (Id, TenNhacSi) VALUES (33, 'Benjamin Levin');