INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (1, 'Love Songs');
INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (2, 'For Love');
INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (3, 'Wedding');
INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (4, 'Merry christmas');
INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (5, 'Cover & Mashup');
INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (6, 'Coffee Time');
INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (7, 'Nhạc phim');
INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (8, 'Thất Tình');
INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (9, 'Nhạc Vàng');
INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (10, 'Bolero');
INSERT INTO webmusic.chude (Id, TenChuDe) VALUES (16, 'Aucosti');